BOOTMAGIC_ENABLE = no       # Enable Bootmagic Lite
MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no         # Console for debug
#KEYBOARD_SHARED_EP = yes    # When console is enabled with Vial on the blackpill, I run out of endpoints.
COMMAND_ENABLE = no         # Commands for debug and configuration
NKRO_ENABLE = yes           # Enable N-Key Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = yes       # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
SPLIT_KEYBOARD = yes
OLED_ENABLE = yes
OLED_DRIVER = ssd1306
CAPS_WORD_ENABLE = yes
ENCODER_ENABLE = no
DYNAMIC_MACRO_ENABLE = yes
SERIAL_DRIVER = usart
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3389
# NO_SUSPEND_POWER_DOWN = yes # Because the blackpill has an issue resuming from sleep
